# Font configuration (changes require restart)
font:
  # The normal (roman) font face to use.
  normal:
    family: Droid Sans Mono Slashed for Powerline
    # Style can be specified to pick a specific face.
    style: Regular

  # The bold font face
  bold:
    family: Droid Sans Mono Slashed for Powerline
    # Style can be specified to pick a specific face.
    style: Bold

  # The italic font face
  italic:
    family: Droid Sans Mono Slashed for Powerline
    # Style can be specified to pick a specific face.
    style: Italic

# Colors (Dracula)
colors:
  # Default colors
  primary:
    background: '0x282a36'
    foreground: '0xf8f8f2'

  # Normal colors
  normal:
    black:   '0x000000'
    red:     '0xff5555'
    green:   '0x50fa7b'
    yellow:  '0xf1fa8c'
    blue:    '0xcaa9fa'
    magenta: '0xff79c6'
    cyan:    '0x8be9fd'
    white:   '0xbfbfbf'

  # Bright colors
  bright:
    black:   '0x575b70'
    red:     '0xff6e67'
    green:   '0x5af78e'
    yellow:  '0xf4f99d'
    blue:    '0xcaa9fa'
    magenta: '0xff92d0'
    cyan:    '0x9aedfe'
    white:   '0xe6e6e6'

# Colors (Nord)
# colors:
#    # Default colors
#    primary:
#      background: '0x2E3440'
#      foreground: '0xD8DEE9'

#    # Normal colors
#    normal:
#      black:   '0x3B4252'
#      red:     '0xBF616A'
#      green:   '0xA3BE8C'
#      yellow:  '0xEBCB8B'
#      blue:    '0x81A1C1'
#      magenta: '0xB48EAD'
#      cyan:    '0x88C0D0'
#      white:   '0xE5E9F0'

#    # Bright colors
#    bright:
#      black:   '0x4C566A'
#      red:     '0xBF616A'
#      green:   '0xA3BE8C'
#      yellow:  '0xEBCB8B'
#      blue:    '0x81A1C1'
#      magenta: '0xB48EAD'
#      cyan:    '0x8FBCBB'
#      white:   '0xECEFF4'
